call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2016.0.110\windows\bin\compilervars.bat" ia32
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gmodules.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2riv7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2str7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2rch8u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2basu1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2hfb7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\xmdlib_2.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\lak_gag_sfr_modules.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2sub7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2gag7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2fhb7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\sparse.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\parutl7.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\cln2props1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\glo2basu1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\disu2gncn1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2drn7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\glo2btnu1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\pcgu7.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2evt8u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2sfr7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2wel7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2chd7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\disu2gncb1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2bcf-lpf-u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2lak7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\utl7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\gwf2ghb7u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\xmd.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\cln2basu1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\glo2sms-u1.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -c /module:mod_temp\ /object:obj_temp\ .\src_temp\mfusg.f
ifort.exe -O2 -heap-arrays:0 -fpe:0 -traceback -o mfusg.exe obj_temp\*.obj
